name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - production
    paths:
      - 'mobile/**'

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: ./mobile/package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build app (preview) on development branch
        if: github.ref == 'refs/heads/main'
        run: eas build --platform all --profile preview --non-interactive

      - name: Build app (production) on production branch
        if: github.ref == 'refs/heads/production'
        run: eas build --platform all --profile production --non-interactive
